### PR TITLE
Bumping resources for controller 50%

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Issue #, if available:*

*Description of changes:*

50% increase to resources.

### CODE REVIEW

**Review by lewisdiamond — CHANGES_REQUESTED** [review]

**Comment by jonahjon** [comment]
/hold
This might be moot since the issue could be from helm looping on create failures.

**Comment by lewisdiamond** [comment]
I'd still push this as there's no real downside if we don't modify the requests.
/lgtm
/approve

**Review by vincentni — APPROVED** [review]

**Pull request merged**
