### PR TITLE
Add tag to bundle images

### PR DESCRIPTION
**Pull request by TerryHowe**
The VersionImages object does not have a version. When we copy the bundle to a private registry, it would be convenient to have one to make tagging the images easy.

### CODE REVIEW

**Comment by jonahjon** [comment]
/lgtm

I'll want to verify this is still working just fine with bundle creation, as the tests for it are not triggered here although it relies on those structs.

**Comment by lewisdiamond** [comment]
Can you add a test case (could simply modify one of the test bundle) that adds an entry in `VersionImages` but has no `Version` defined?

**Comment by TerryHowe** [comment]
It appears the signing script does not generate the correct signature when the version is not specified.

**Comment by jonahjon** [comment]
although you might have to manually merge this due to the test failures.

**Comment by TerryHowe** [comment]
Closes: https://github.com/aws/eks-anywhere-packages/issues/799

**Pull request merged**
