### PR TITLE
Support cluster specific ca.crt and insecure

### PR DESCRIPTION
**Pull request by TerryHowe**
Add support for cluster specific configuration:
* cluster specific ca.crt file
* cluster specific insecure file
* cluster specific credentials config.json file

The existence of the insecure file indicates insecure mode.

### CODE REVIEW

**Comment by TerryHowe** [comment]
Waiting for what Vincent approval/ecr-token-refresher changes

**Review by vincentni — APPROVED** [review]
/lgtm

**Comment by vincentni** [comment]
> Waiting for what Vincent approval/ecr-token-refresher changes

https://github.com/aws/eks-anywhere-packages/pull/792

**Pull request merged**
