### PR TITLE
Add packages input files for private ECR bundle generation

### PR DESCRIPTION
**Pull request by abhay-krishna**
Add packages input files for private ECR bundle generation.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by d8660091** [comment]
Would it be better to call the yaml file "regional" instead of "new"? And will each codebuild run populate just 1 region?

**Comment by abhay-krishna** [comment]
> Would it be better to call the yaml file "regional" instead of "new"? And will each codebuild run populate just 1 region?

Yeah I like that naming. Will change it. And yes it's building in one region only and being replicated to other regions.

**Review by d8660091 — COMMENTED** [review]
/LGTM

**Pull request merged**
