### PR TITLE
Lift registry

### PR DESCRIPTION
**Pull request by ewollesen**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ewollesen** [comment]
/hold 

Until #757 merges

**Comment by ewollesen** [comment]
This is the same concept as 757, but for the OCIRegistryClient.

**Review by TerryHowe — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
