### PR TITLE
Change 1d to 24h

### PR DESCRIPTION
**Pull request by a-cool-train**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — CHANGES_REQUESTED** [review]
Isn't it getting this default from the api code?

**Comment by TerryHowe** [comment]
> What promoted this change?

This used to work, but no longer does. I assume a k8s change

**Comment by a-cool-train** [comment]
> Isn't it getting this default from the api code?

Yes you are right. I just fixed it.

**Review by TerryHowe — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
