### PR TITLE
Get image tags from files

### PR DESCRIPTION
**Pull request by TerryHowe**
Pull the image tags from files for now so we can modify them easily

### CODE REVIEW

**Comment by jonahjon** [comment]
Works all good

**Comment by TerryHowe** [comment]
> @TerryHowe where do you see us pulling them from in the future?

I'm not sure, but this will work well if we are going to put these in manually or using a bot. More deterministic than "latest" at least, people will know what they are getting.

**Review by jonahjon — APPROVED** [review]

**Pull request merged**
