### PR TITLE
Adding packages to staging artifact move file

### PR DESCRIPTION
**Pull request by jonahjon**
*Issue #, if available:*

*Description of changes:*

Move Packages latest release to artifact move, so we can start scanning images better.

It's a static tag now since that was the last release candidate image to go to prod.

### CODE REVIEW

**Comment by jonahjon** [comment]
For https://github.com/aws/modelrocket-add-ons/issues/271

**Comment by ivyostosh** [comment]
/lgtm
Verified `v0.2.30-eks-a-v0.0.0-dev-release-0.14-build.206` version exists in https://gallery.ecr.aws/l0g8r8j6/eks-anywhere-packages

**Pull request merged**
