### PR TITLE
Bring in Cobra and Viper

### PR DESCRIPTION
**Pull request by TerryHowe**
Closes: https://github.com/aws/eks-anywhere-packages/issues/656

### CODE REVIEW

**Comment by TerryHowe** [comment]
Closes: https://github.com/aws/eks-anywhere-packages/issues/656

**Comment by jonahjon** [comment]
The new main.go almost looks quite slim and maybe not too useful to have anymore.

Everything else looks good.

/lgtm
/approve

**Comment by jonahjon** [comment]
you can /approve when you're ready to merge.

**Pull request merged**
