### PR TITLE
Use the package-manager command everywhere

### PR DESCRIPTION
**Pull request by TerryHowe**
Missed the deployment `package-manager` command change until I functionally tested it

### CODE REVIEW

**Review by vincentni — APPROVED** [review]
/lgtm
/approve

**Comment by TerryHowe** [comment]
> This Dockerfile also needs changed as well. https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/aws/eks-anywhere-packages/docker/linux/eks-anywhere-packages/Dockerfile


Yeh, but I need this to merge first so I can open my build tooling PR

**Comment by TerryHowe** [comment]
The docker file in this repo is confusing and useless right now

**Comment by junshun** [comment]
I think its only use is for local testing

**Pull request merged**
