### PR TITLE
Add spec copy to package and pbc status

### PR DESCRIPTION
**Pull request by TerryHowe**
In order for us to tell what has changed during reconciliation, we need to keep a copy of the previous state. There are a few things for example that should be immutable like `targetNamespace` in package and we can't detect a change there unless we know the previous value.

### CODE REVIEW

**Comment by TerryHowe** [comment]
/hold

Not for a bug release, should be December release

**Comment by lewisdiamond** [comment]
We probably should keep that state elsewhere. Using the status to keep the previous spec works only for changes, not for deletes. Related to https://github.com/aws/eks-anywhere-packages/issues/15 and https://github.com/aws/eks-anywhere-packages/issues/202

**Comment by TerryHowe** [comment]
> We probably should keep that state elsewhere. Using the status to keep the previous spec works only for changes, not for deletes. Related to #15 and #202


Deletes are a different problem. I assumed we were going to user a label or annotation for CR deletes while the controller is down. https://github.com/aws/eks-anywhere-packages/issues/202 is another problem not related to deletes or updates. It is about someone changing the installed package instead of the package CR

**Comment by TerryHowe** [comment]
/hold

wait for this next release at this point

**Comment by TerryHowe** [comment]
https://github.com/aws/eks-anywhere-packages/issues/512 depends on this for example

**Pull request merged**
