### PR TITLE
Bumping cluster autoscaler tag

### PR DESCRIPTION
**Pull request by junshun**
Bumping autoscaler tags to production

### CODE REVIEW

**Comment by junshun** [comment]
/hold
Waiting for suppression rule updates

**Comment by ivyostosh** [comment]
You need to update https://github.com/aws/eks-anywhere-packages/blob/main/generatebundlefile/data/prod_artifact_move.yaml and https://github.com/aws/eks-anywhere-packages/blob/main/generatebundlefile/data/staging_artifact_move.yaml as well

**Comment by junshun** [comment]
done
/unhold

**Pull request merged**
