### PR TITLE
Fix bundle states

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by ivyostosh** [comment]
I like the new states! Much cleaner than before. I'm just also wondering, how do you differentiate "ignored" with "invalid version"?

**Comment by TerryHowe** [comment]
> I like the new states! Much cleaner than before. I'm just also wondering, how do you differentiate "ignored" with "invalid version"?


ignored is in an unmonitored namespace and invalid version has a name that we do not recognize

**Comment by ivyostosh** [comment]
So is this a correct map from the previous states to the current states:
- inactive, active, active (upgrade available) -> available
- ignored -> ignored
- ignored version, invalid version -> invalid version

**Comment by TerryHowe** [comment]
> So is this a correct map from the previous states to the current states:
> 
> * inactive, active, active (upgrade available) -> available
> * ignored -> ignored
> * ignored version, invalid version -> invalid version


ingored version gets mapped to available now. ingored version was for a version of k8s that did not match the server version

**Comment by ivyostosh** [comment]
> * inactive, active, active (upgrade available) -> available
> * ignored -> ignored
> * ignored version, invalid version -> invalid version

So in summary - a map from the previous states to the current states:
inactive, active, active (upgrade available), ignored version -> available
ignored -> ignored
invalid version -> invalid version

**Pull request merged**
