### PR TITLE
Fixing bundle gen dependencies field

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by a-cool-train** [comment]
Can you pull from main? The PR looks good overrall.

**Comment by TerryHowe** [comment]
> Can you pull from main? The PR looks good overrall.

Ah, yeh, this branch is out of date

**Comment by jonahjon** [comment]
> > Can you pull from main? The PR looks good overrall.
> 
> Ah, yeh, this branch is out of date

That's interesting since I created it about 1 minute ago XD

**Pull request merged**
