### PR TITLE
Add cluster-autoscaler to prod bundle

### PR DESCRIPTION
**Pull request by jonathanmeier5**
*Issue #, if available:*
Epic: https://github.com/aws/eks-anywhere/issues/3186
Ticket: https://github.com/aws/eks-anywhere/issues/3727

*Description of changes:*
Add cluster-autoscaler to prod bundle.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jonathanmeier5** [comment]
yikes!

**Comment by jonahjon** [comment]
We should doublecheck if this is still accurate

**Pull request merged**
