### PR TITLE
Remove export test

### PR DESCRIPTION
**Pull request by TerryHowe**
One of these wasn't used, the other it would be easier to make it public.

### CODE REVIEW

**Comment by ewollesen** [comment]
I'm against exporting a function solely so it can be tested from another package.

Non-exported methods should not be tested from other packages.

Making an non-exported method exported, simply so you can test it, is dangerous. Once exported, we can no longer change this function without the risk of breaking others. We should be careful about what we export, and not do it just to aid an artificial barrier in our testing.

**Comment by TerryHowe** [comment]
> I'm against exporting a function solely so it can be tested from another package.

Okay, but I just replaced one export for another.

**Comment by TerryHowe** [comment]
Just put the test in the same package

**Review by ewollesen — APPROVED** [review]
/lgtm

**Pull request merged**
