### PR TITLE
Remove empty status from Bundle struct.

### PR DESCRIPTION
**Pull request by jonahjon**
*Description of changes:*

Adding new Go struct to omit status when creating bundle.

```
spec:
  kubeVersion: "1.21"
  packages:
  - name: hello-eks-anywhere
    source:
      registry: public.ecr.aws/l0g8r8j6
      repository: aws-containers/hello-eks-anywhere
      versions:
      - digest: sha256:fee760d31e2fd23309ec8399d50378b075a3aa3ddbcb0afdc501eb6a0e48a541
        name: 0.1.0_c4e25cb42e9bb88d2b8c2abfbde9f10ade39b214
status:
  spec:
    packages: null
  state: ""
```

Becomes

```
spec:
  kubeVersion: "1.21"
  packages:
  - name: hello-eks-anywhere
    source:
      registry: public.ecr.aws/l0g8r8j6
      repository: aws-containers/hello-eks-anywhere
      versions:
      - digest: sha256:fee760d31e2fd23309ec8399d50378b075a3aa3ddbcb0afdc501eb6a0e48a541
        name: 0.1.0_c4e25cb42e9bb88d2b8c2abfbde9f10ade39b214
```

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

What no hacky string manipulation? Alarms are kind of going off here, but I can roll with this for now.

**Comment by jonahjon** [comment]
> /lgtm
> 
> What no hacky string manipulation? Alarms are kind of going off here, but I can roll with this for now.

Can't tell if that's a good or bad thing.

**Review by ewollesen — COMMENTED** [review]
/lgtm

**Comment by ewollesen** [comment]
> > /lgtm
> > What no hacky string manipulation? Alarms are kind of going off here, but I can roll with this for now.
> 
> Can't tell if that's a good or bad thing.

Depends on if you like getting woken up in the middle of the night whle on call. :P

**Pull request merged**
