### PR TITLE
Update to oras 0.15

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by TerryHowe** [comment]
@jonahjon

**Comment by jonahjon** [comment]
Have we tested this?

If not let me try and test all the CLI commands to make sure it doesn't break out CI

**Comment by TerryHowe** [comment]
> Have we tested this?
> 
> If not let me try and test all the CLI commands to make sure it doesn't break out CI

I don't have the capability to test it completely, so basically unit tested, but not functionally

**Pull request closed without merging**
